blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/registration', views.Registration_views.as_view(), name='registration'),
    path('accounts/login/', views.userlogin, name='login'),
    path('accounts/logout/', views.userlogout, name='logout'),
    path('accounts/password_change', views.change_password, name='password_change'),
    path('accounts/password_change/done', views.change_password_done, name='password_change_done'),
    # Password Reset or Password Forget
    # https://docs.djangoproject.com/en/3.0/topics/auth/default/#using-the-views
    path('accounts/reset_password/', auth_views.PasswordResetView.as_view(template_name = "user/reset_password.html"), name ='reset_password'),
    path('accounts/reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = "user/password_reset_sent.html"), name ='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = "user/password_reset_form.html"), name ='password_reset_confirm'),
    path('accounts/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = "user/password_reset_done.html"), name ='password_reset_complete'),
    path('post/view_post/<int:id>', views.view_post, name='view_post'),
    path('subscribe', views.subscribe, name='subscribe'),
    path('comments/<int:id>', views.CommentsView.as_view(), name="comments"),
    path('search_item', views.search_view, name="search_item"),
    path('contact_us/', views.contact_us, name='contact_us')
]

multiblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Category, Post, EmailSubscribe, Comments
from django.views import View
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import Password_Change_Form, EmailSendForm
from django.core.mail import send_mail
from django.db.models import Q
# Create your views here.


def home(request):
    feature_post = Post.objects.filter(status='active', featured=True, visible=True).order_by('category', '-created_date')[:5]
    
    context={
        'f_post': feature_post.first(),
        's_post': feature_post[1],
        'last_post': feature_post[2:]
    }
    
    return render(request, 'pages/home.html', context)

class Registration_views(View):
    def get(self, request):
        return render(request, 'user/registration.html')

    def post(self, request):
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        if password1 == password2:
            user_check = authenticate(username=username, password=password1)
            if user_check is None:
                try:                    
                    User.objects.create_user(first_name=fname, last_name=lname, email=email, username=username, password=password1)
                    messages.success(request, "Sign Up Successfully.")
                except Exception as errors:
                    messages.error(request, "Username Already Exist.")
            else:
                messages.error(request, "Username Already Exist.")
        else:
            messages.error(request, "Password not match.")
        return render(request, 'user/registration.html')


def change_password(request):
    if request.method == 'POST':
        forms = Password_Change_Form(request.user, request.POST)
        if forms.is_valid():
            forms.save()
            update_session_auth_hash(request, request.user)
            return redirect('change_password_done')
    else:
        forms = Password_Change_Form(request.user)
    context = {
        'forms':forms
    }
    return render(request, 'user/changepassword.html', context)


def change_password_done(request):
    return render(request, 'user/change_password_done.html')


def userlogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user_obj = authenticate(username=username, password=password)
        if user_obj is not None:
            login(request, user_obj)
            return redirect('home')
        else:
            messages.error(request, "Username or Password Invalid.")
    return render(request, 'user/login.html')


def userlogout(request):
    logout(request)
    return redirect('home')


def contact_us(request):
    forms = EmailSendForm()
    if request.method == 'POST':
        forms = EmailSendForm(request.POST)
        if forms.is_valid():
            subject = forms.cleaned_data['subject']
            sender = forms.cleaned_data['sender']
            message = forms.cleaned_data['message']
            recipients = ['mailzahidul@gmail.com']
            send_mail(subject, message, sender, recipients)
            if request.user.is_authenticated:
                user = request.user
                obj = forms.save(commit=True)
                obj.sender_user=user
                obj.sender=user.email
                obj.save()
                return redirect('contact_us')
            forms.save()
            return redirect('contact_us')
        else:
            messages.error(request, forms.errors)
    context={
        'forms':forms
    }
    return render(request, 'pages/contact_us.html', context)


def view_post(request, id):
    post_obj = get_object_or_404(Post, id=id)
    post_obj.visit_count=post_obj.visit_count+1
    post_obj.save()
    related_post = Post.objects.filter(category=post_obj.category, author=post_obj.author).exclude(id=id).order_by('-id')[:4]
    first = related_post.first()
    rest_post = related_post[1:]
    context = {
        'post_obj':post_obj,
        'related_post':related_post,
        'first':first,
        'rest_post':rest_post
    }
    return render( request, 'post/view_post.html', context)


def subscribe(request):
    if request.method == 'POST':
        sub_email = request.POST['subscribe']
        obj_email = EmailSubscribe.objects.filter(email=sub_email)
        if obj_email:
            messages.warning(request, "This Email Already Subscribe")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            obj = EmailSubscribe(email=sub_email)
            obj.save()
            messages.success(request, "Thanks for Subscribe...")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class CommentsView(View):
    def post(self, request, id):
        post = get_object_or_404(Post, id=id)
        name = request.POST['name']
        body = request.POST['body']
        comm = Comments(post=post, name=name, body=body).save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def search_view(request):
    q = request.GET.get('search_item')
    post = Post.objects.filter(status='active', visible=True)
    if len(q) > 100:
        posts = post.none()
    else:
        posts = post.filter(
            Q(title__icontains=q) | 
            Q(description__icontains=q) | 
            Q(category__name__icontains=q) | 
            Q(author__author__username__icontains=q)
            )
    context = {
        'items':posts,
        'search':q
    }
    return render(request, 'pages/search.html', context)

templates/pages/contact_us.html
{% extends 'base.html' %}


{% block title %} Contact Page {% endblock %}

{% block content %}
<div class="container mb-3">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="alert{% if message.tags %} {{ message.tags }} {% endif %}" role="alert">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        {% endfor %}
    </div>
    {% endif %}
    <h1 class="">Contact Page</h1>
    <hr>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto assumenda adipisci eius saepe consequuntur
        rem, facilis praesentium! Asperiores quasi necessitatibus ea deleniti sed dolor sint, dignissimos quas mollitia,
        fugit quod.</p>



    <div class="row p-3" data-aos="fade-in">

        <div class="col-lg-6 d-flex align-items-stretch">
            <div class="info">
                <div class="address">
                    
                    <h4><i class="fas fa-map-marker-alt"></i> Location:</h4>
                    <p>Uttarkhan, Dhaka-1230, Bangladesh</p>
                </div>

                <div class="email">
                    <h4><i class="fas fa-envelope"></i> Email :</h4>
                    <p>mailzahidul@gmail.com</p>
                </div>

                <div class="phone">
                    <h4><i class="fas fa-phone"></i> Cell:</h4>
                    <p>+880 1919100108</p>
                </div>

                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d29187.82692638952!2d90.42564988818175!3d23.872650104122187!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c5d8f1530779%3A0xbf172b1d71a988a6!2sUttar%20Khan%2C%20Dhaka!5e0!3m2!1sen!2sbd!4v1619154090928!5m2!1sen!2sbd"
                    frameborder="0" style="border:0; width: 100%; height: 290px;" allowfullscreen=""></iframe>
            </div>

        </div>




        <div class="col-lg-6 mt-5 mt-lg-0 d-flex align-items-stretch">
            <div class="card">
                <div class="card-header">Write your quary
                </div>
                <div class="card-body">
    <!-- <form action="" method="POST">
        {% csrf_token %}
        {{ forms }}
        <input type="submit" value="Send">
    </form> -->


    <!-- <form action="" method="POST">
        {% csrf_token %}
         {% for form in forms %}
        <div class="mb-3">
            {{ form }}
        </div>
        {% endfor %}
    </form> -->
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% if request.user.is_authenticated %}
                        <div class="mb-3">
                            <input type="text" name="subject" class="form-control" maxlength="100" required="" placeholder="Subject"
                                id="id_subject">
                        </div>
                        <div class="mb-3">
                            <textarea name="message" cols="40" rows="10" class="form-control" required=""
                                id="id_message"></textarea>
                        </div>
                        {% else %}
                        <div class="mb-3">
                            <input type="email" name="sender" class="form-control" placeholder="Email" maxlength="254"
                                required="" id="id_sender">
                        </div>
                        <div class="mb-3">
                            <input type="text" name="subject" class="form-control" maxlength="100" required=""  placeholder="Subject"
                                id="id_subject">
                        </div>
                        <div class="mb-3">
                            <textarea name="message" cols="40" rows="10" class="form-control" required="" 
                                id="id_message"></textarea>
                        </div>
                        {% endif %}


                        <input type="submit" value="Send">
                    </form>
                </div>
            </div>


        </div>

    </div>

</div>

{% endblock %}

templates/pages/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} MultiBlogs {% endblock %}
{% block content %}


<div class="container">
	<div class="jumbotron jumbotron-fluid mb-3 pt-0 pb-0 bg-lightblue position-relative">
		<div class="pl-4 pr-0 h-100 tofront">
			<div class="row justify-content-between">
				<div class="col-md-6 pt-6 pb-6 align-self-center">
					<h2 class="secondfont mb-3 font-weight-bold">Where idea explosion!!!</h2>
					<p class="mb-3">
						Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, harum excepturi? Tempora
						voluptate earum, atque quia recusandae iure quos maiores? Sequi iste quam necessitatibus
						consequatur deleniti saepe unde et ab!
					</p>

					<a href="#" class="btn btn-dark">Read More</a>
				</div>
				<div class="col-md-6 d-none d-md-block pr-0"><img style="background-size: cover;"
						src="{% static 'images/blog.jpeg' %}" alt=""> </div>
			</div>
		</div>
	</div>
</div>



<div class="container py-4 " style="margin-bottom: 70px;">
	<div class="row">
		<div class="col-lg-6">

			<div class="card border-0 mb-4 box-shadow h-xl-300">
				<div>
					<img src="{% static 'images/blog2.jpg' %}"
						style="height: 200px; background-size: cover; background-repeat: no-repeat; width: 100%;"
						alt="">
				</div>
				<div class="card-body px-0 pb-0 d-flex flex-column align-items-start">
					<h2 class="h4 font-weight-bold">
						<a class="text-dark" href="{% url 'view_post' s_post.id %}"> {{ s_post.title }}</a>
					</h2>
					<p class="card-text">
						{{ s_post.description|truncatechars:150 }}
					</p>
					<div>
						<small class="d-block">
							{% if s_post.author.author_img %}
							<img height="20" class="rounded-circle shadow" style="border-radius: 50%;"
								src="{{ s_post.author.author_img.url }}">
							{% else %}
							<img class="rounded-circle shadow" height="20"
								src="https://www.pngarts.com/files/11/Avatar-PNG-Transparent-Image.png" alt="">
							{% endif %}
							<a class="text-muted" href="#">{{s_post.author.author.username}}</a></small>
						<small class="text-muted">{{ s_post.created_date | timesince }} ago . {{s_post.visit_count}}
							views</small>
					</div>
				</div>
			</div>
		</div>

		<div class="col-lg-6">
			<div class="flex-md-row mb-4 box-shadow h-xl-300">
				
					{% for post in last_post %}
					<div class="mb-3 d-flex align-items-center">
						{% if post.image %}
						<img height="20" width="20" src="{{ post.image.url }}">
						{% else %}
						<img height="20" width="20" src="{% static 'empty.jpg' %}">
						{% endif %}
						<div class="pl-3">
							<h2 class="mb-2 h6 font-weight-bold">
								<a class="text-dark" href="{% url 'view_post' post.id %}">{{ post.title }}</a>
							</h2>
							<div class="card-text text-muted small">
								{{ post.description }}
							</div>
							<small class="text-muted">{{ post.created_date | timesince }}. Views {{ post.visit_count }}</small>
						</div>
					</div>
					{% endfor %}
				

			</div>
		</div>

	</div>
</div>



<div class="container">
	<div class="row justify-content-between">
		<div class="col-md-8">
			<h5 class="font-weight-bold spanborder"><span>All Stories</span></h5>

			{% for p in last_post %}
			<div class="mb-3 d-flex justify-content-between">
				<div class="pr-3">
					<h2 class="mb-1 h4 font-weight-bold">
						<a class="text-dark" href="{% url 'view_post'  p.id %}">{{ p.title }}</a>
					</h2>
					<p>
						{{ p.description | truncatechars:100 }}
					</p>
					<div class="card-text text-muted small">
						{% if p.author.author_img %}
						<img height="20" class="rounded-circle shadow" style="border-radius: 50%;"
							src="{{ p.author.author_img.url }}">
						{% else %}
						<img class="rounded-circle shadow" height="20"
							src="https://www.pngarts.com/files/11/Avatar-PNG-Transparent-Image.png" alt="">
						{% endif %}
						{{ p.author.author.username }} in <a class="text-dark" href="">{{ p.catagories.name }} </a>

					</div>
					<small class="text-muted">{{p.created_date|timesince }} ago ; {{ p.visit_count}} views </small>
				</div>
				<img height="120" src="{{ p.image_url }}">
			</div>
			{% endfor %}


		</div>
		<div class="col-md-4 pl-4">
			<h5 class="font-weight-bold spanborder"><span>Popular</span></h5>
			<ol class="list-featured">
				{% for p in last_post %}
				<li>
					<span>
						<h6 class="font-weight-bold">
							<a href="{% url 'view_post' p.id %}" class="text-dark">{{ p.title }}</a>
						</h6>
						<p class="text-muted"> {{p.category.name}}</p>
					</span>
				</li>
				{% endfor %}
				<!-- <li>
					<span>
						<h6 class="font-weight-bold">
							<a href="#" class="text-dark">Humans Reversing Climate Clock: 50 Million Years</a>
						</h6>
						<p class="text-muted">
							Jake Bittle in SCIENCE
						</p>
					</span>
				</li>
				<li>
					<span>
						<h6 class="font-weight-bold">
							<a href="#" class="text-dark">Unprecedented Views of the Birth of Planets</a>
						</h6>
						<p class="text-muted">
							Jake Bittle in SCIENCE
						</p>
					</span>
				</li>
				<li>
					<span>
						<h6 class="font-weight-bold">
							<a href="#" class="text-dark">Effective New Target for Mood-Boosting Brain Stimulation
								Found</a>
						</h6>
						<p class="text-muted">
							Jake Bittle in SCIENCE
						</p>
					</span>
				</li>
				<li>
					<span>
						<h6 class="font-weight-bold">
							<a href="#" class="text-dark">Did Supernovae Kill Off Large Ocean Animals?</a>
						</h6>
						<p class="text-muted">
							Jake Bittle in SCIENCE
						</p>
					</span>
				</li> -->
			</ol>
		</div>
	</div>
</div>
{% endblock %}

templates/pages/search.html
{% extends 'base.html' %}

{% block title %} {{ search }} | MultiBlogs {% endblock %}
{% block content %}
<div class="container pt-4 pb-4 " style="margin-bottom: 70px;">
    {% if items %}
    <h3> Showing Result of : <b>{{ search }}</b></h3>
    <br>
    <div class="row">

        {% for i in items %}

        <div class="col-lg-3">

            <div class="card border-0 mb-4 box-shadow h-xl-300" style=" box-shadow: 1px 2px 5px 6px #ececec; padding: 10px;">
                <div class="card-top-img text-center">
                    <img  class="img-thumbnail" width="100px" height="120px"  src="{{ i.image.url }}" alt="">
                </div>
                <div class="card-body px-0 pb-0 d-flex flex-column align-items-start">
                    <h2 class="h4 font-weight-bold">
                        <a class="text-dark" href="{% url 'view_post' i.id %}"> {{ i.title | truncatechars:30}} </a>
                    </h2>
                    <p class="card-text">
                        {{i.description|truncatechars:30}}
                    </p>
                    <div>
                        <small class="d-block">
                            <a class="text-muted" href=" ">{{i.author.author.username}}</a> in {{ i.category}}</small>
                        <small class="text-muted">{{ i.created_date | timesince }} ago . {{i.visit_count}} views</small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    {% else %}
    <div class="col-lg-10 " style="margin:0 auto;">
        <h3>Your search - <b>{{ search }}</b> - did not match any documents.</h3>

        <h5> Suggestions: </h5>
        <ul>
            <li> Make sure that all words are spelled correctly.</li>
            <li> Try different keywords.</li>
            <li> Try more general keywords.</li>
            <li> Try fewer keywords.</li>
        </ul>

    </div>
    {% endif %}
</div>
{% endblock %}