blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/registration', views.Registration_views.as_view(), name='registration'),
    path('accounts/login/', views.userlogin, name='login'),
    path('accounts/logout/', views.userlogout, name='logout'),
    path('accounts/password_change', views.change_password, name='password_change'),
    path('accounts/password_change/done', views.change_password_done, name='password_change_done'),
    # Password Reset or Password Forget
    # https://docs.djangoproject.com/en/3.0/topics/auth/default/#using-the-views
    path('accounts/reset_password/', auth_views.PasswordResetView.as_view(template_name = "user/reset_password.html"), name ='reset_password'),
    path('accounts/reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = "user/password_reset_sent.html"), name ='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = "user/password_reset_form.html"), name ='password_reset_confirm'),
    path('accounts/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = "user/password_reset_done.html"), name ='password_reset_complete'),
    path('post/view_post/<int:id>', views.view_post, name='view_post'),
    path('subscribe', views.subscribe, name='subscribe'),
    path('comments/<int:id>', views.CommentsView.as_view(), name="comments"),
    path('search_item', views.search_view, name="search_item"),
    path('contact_us/', views.contact_us, name='contact_us')
]

multiblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(null=True, upload_to='category/', blank=True)
    created_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Category"

    def __str__(self):
        return self.name
        

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

STATUS = (
    ('active', 'Activae'),
    ('deactive', 'Deactivae')
)


class EmailSend(models.Model):
    sender_user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    sender = models.EmailField(blank=True)
    subject = models.CharField(max_length=100)
    message = models.TextField()
    send_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Email Send'

    def __str__(self):
        return self.sender


DESIGNATION = (
('admin', 'Admin'),
('editor', 'Editor'),
('modarator', 'Modarator')
)



class Author(models.Model):
    author = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField()
    designation = models.CharField(choices=DESIGNATION, max_length=20)
    author_img = models.ImageField(upload_to="author/", blank=True, null=True)
    author_status = models.CharField(choices=STATUS, max_length=12)

    class Meta:
        verbose_name_plural = "Author"

    def __str__(self):
        return self.first_name + self.last_name


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to = "blog/feature_image/", blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    status = models.CharField(choices=STATUS, max_length=10, default='active')
    featured = models.BooleanField(default=False)
    visit_count = models.IntegerField(default=0)
    visible = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Post"

    def __str__(self):
        return self.title


class EmailSubscribe(models.Model):
    email = models.EmailField()
    subscribe_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=50)
    body = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

templates/post/view_post.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{post_obj.title}} {% endblock %}

{% block content %}
<div class="container">
	<div class="jumbotron jumbotron-fluid bg-white position-relative">
		<div class="h-100 tofront">
			<div class="row justify-content-between">
				{% if messages %}
				<div class="messages">
					{% for message in messages %}
					<div class="alert{% if message.tags %} {{ message.tags }} {% endif %}" role="alert">{{ message }}
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>

					{% endfor %}
				</div>
				{% endif %}

				<div class="col-md-6 pt-6 pb-6 pr-6 align-self-center">
					<p class="text-uppercase font-weight-bold">
						<a class="text-danger" href="">{{ post_obj.category }}</a>
					</p>
					<h1 class="display-4 secondfont mb-3 font-weight-bold">{{ post_obj.title }}</h1>
					<p class="mb-3">{{ post_obj.description }}</p>
					<div class="d-flex align-items-center">
						{% if post_obj.author.author_img %}
						<img class="rounded-circle shadow" src="{{ post_obj.author.author_img.url }}" alt="">
						{% else %}
						<img class="rounded-circle shadow"
							src="https://www.pngarts.com/files/11/Avatar-PNG-Transparent-Image.png" alt="">
						{% endif %}

					</div>
				</div>
				<div class="col-md-6 pr-0">
					<img src="{{ post_obj.image.url }}" alt="">
				</div>
			</div>

		</div>

	</div>
</div>

<div class="container pt-4 pb-4">
	<div class="row justify-content-center">
		<div class="col-lg-2 pr-4 mb-4 col-md-12">
			<div class="sticky-top text-center">
				<div class="text-muted">
					Share this
				</div>
				<div class="share d-inline-block">
					<!-- AddToAny BEGIN -->
					<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
						<a class="a2a_dd" href="https://www.addtoany.com/share"></a>
						<a class="a2a_button_facebook"></a>
						<a class="a2a_button_twitter"></a>
					</div>
					<script async src="https://static.addtoany.com/menu/page.js"></script>
					<!-- AddToAny END -->
				</div>
			</div>
		</div>
		<div class="col-md-12 col-lg-8">
			<div class="border p-5 bg-lightblue">
				<div class="row justify-content-between">
					<div class="col-md-5 mb-2 mb-md-0">
						<h5 class="font-weight-bold secondfont">Become a member</h5>
						Get the latest news right in your inbox. We never spam!
					</div>
					<div class="col-md-7">
						<form action="{% url 'subscribe' %}" method="POST">
							<div class="row">

								{% csrf_token %}
								<div class="col-md-12">
									<input type="email" name='subscribe' class="form-control"
										placeholder="Enter your e-mail address" required>
								</div>
								<div class="col-md-12 mt-2">
									<button type="submit" class="btn btn-success btn-block">Subscribe</button>
								</div>

							</div>
						</form>
					</div>
				</div>
			</div>

			<form style="margin-top:50px;" action="{% url 'comments' post_obj.id %}" method="POST">
				{% csrf_token %}
				<div class="row form-group">
					<div class="col">
						<input type="text" name='name' class="form-control" placeholder="Your Name">
					</div>
				</div>
				<div class="form-group">
					<textarea class="form-control" name='body' id="exampleFormControlTextarea1" rows="4"></textarea>
				</div>
				<button type="submit" class="btn btn-primary btn-round">Submit Comment </button>
			</form>
			<br>


			{% for p in post_obj.comments_set.all reversed %}
			{% if forloop.counter|divisibleby:2 %}
			<div style="border-radius: 10px; margin: 5px; padding: 25px; background-color: #d8d8d8; ">
				<p><strong>{{ p.name }}</strong> at {{ p.comment_date }}</p>
				<p style="padding: 20px; background-color: #f1f1f1; border-radius: 7px; border:0.5px solid #c5c5c5">{{p.body }}</p>
			</div>
			{% else %}
			<div style="border-radius: 10px; margin: 5px; padding: 25px; background-color: #b3d3c0;">
				<p><strong>{{ p.name }}</strong> at {{ p.comment_date }}</p>
				<p style="padding: 20px; background-color: #c5e6d3; border-radius: 7px; border:0.5px solid #c5c5c5">{{p.body }}</p>
			</div>
			{% endif %}
			{% endfor %}
		</div>
	</div>
</div>

<div class="container pt-4 pb-4">
	<h5 class="font-weight-bold spanborder"><span>Read next</span></h5>
	
	<div class="row">
		
		<div class="col-lg-6">
			
			<div class="card border-0 mb-4 box-shadow h-xl-300">
				<div style="background-image: url(./assets/img/demo/3.jpg); ">
					<img src="{{ first.image.url }}" style="height: 200px; background-size: cover; background-repeat: no-repeat; width: 100%;" alt="">
				</div>
				<div class="card-body px-0 pb-0 d-flex flex-column align-items-start">
					<h2 class="h4 font-weight-bold">
					<a class="text-dark" href="{% url 'view_post' first.id %}"> {{ first.title}} </a>
					</h2>
					<p class="card-text">
						{{first.description|truncatechars:150}}
					</p>
					<div>
						<small class="d-block">
						{% if first.author.author_img %}
						    <img height="20" class="rounded-circle shadow" style="border-radius: 50%;" src="{{ first.author.author_img.url }}">
                        {% else %}
                            <img class="rounded-circle shadow" height="20" src="https://www.pngarts.com/files/11/Avatar-PNG-Transparent-Image.png" alt=""> 
                        {% endif %}
						<a class="text-muted" href="./author.html">{{first.author.author.username}}</a></small>
						<small class="text-muted">{{ first.created_date | timesince }} ago .  {{first.visit_count}} views</small>
					</div>
				</div>
			</div>
			
		</div>
		
		<div class="col-lg-6">
			
			<div class="flex-md-row mb-4 box-shadow h-xl-300">
				{% for p in rest_post %}
				<div class="mb-3 d-flex align-items-center">
					<img height="80" src="{{p.image.url}}">
					<div class="pl-3">
						<h2 class="mb-2 h6 font-weight-bold">
						<a class="text-dark" href="{% url 'view_post' p.id %}">{{p.title}}</a>
						</h2>
						<div class="card-text text-muted small">
						{% if p.author.author_img %}
						    <img height="20" class="rounded-circle shadow" style="border-radius: 50%;" src="{{ p.author.author_img.url }}">
                        {% else %}
                            <img class="rounded-circle shadow" height="20" src="https://www.pngarts.com/files/11/Avatar-PNG-Transparent-Image.png" alt=""> 
                        {% endif %}
                        {{ p.author.author.username }} in <a class="text-dark" href="#">{{p.catagory }} </a>
						
						</div>
						<small class="text-muted">{{ p.created_date | timesince }} ago .  {{p.visit_count}} views</small>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>

{% endblock %}