blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/registration', views.Registration_views.as_view(), name='registration'),
    path('accounts/login/', views.userlogin, name='login'),
    path('accounts/logout/', views.userlogout, name='logout'),
    path('accounts/password_change', views.change_password, name='password_change'),
    path('accounts/password_change/done', views.change_password_done, name='password_change_done'),
    # Password Reset or Password Forget
    # https://docs.djangoproject.com/en/3.0/topics/auth/default/#using-the-views
    path('accounts/reset_password/', auth_views.PasswordResetView.as_view(template_name = "user/reset_password.html"), name ='reset_password'),
    path('accounts/reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = "user/password_reset_sent.html"), name ='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = "user/password_reset_form.html"), name ='password_reset_confirm'),
    path('accounts/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = "user/password_reset_done.html"), name ='password_reset_complete'),
    path('post/view_post/<int:id>', views.view_post, name='view_post'),
    path('subscribe', views.subscribe, name='subscribe'),
    path('comments/<int:id>', views.CommentsView.as_view(), name="comments"),
    path('search_item', views.search_view, name="search_item"),
    path('contact_us/', views.contact_us, name='contact_us')
]

multiblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(null=True, upload_to='category/', blank=True)
    created_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Category"

    def __str__(self):
        return self.name
        

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

STATUS = (
    ('active', 'Activae'),
    ('deactive', 'Deactivae')
)


class EmailSend(models.Model):
    sender_user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    sender = models.EmailField(blank=True)
    subject = models.CharField(max_length=100)
    message = models.TextField()
    send_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Email Send'

    def __str__(self):
        return self.sender


DESIGNATION = (
('admin', 'Admin'),
('editor', 'Editor'),
('modarator', 'Modarator')
)



class Author(models.Model):
    author = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField()
    designation = models.CharField(choices=DESIGNATION, max_length=20)
    author_img = models.ImageField(upload_to="author/", blank=True, null=True)
    author_status = models.CharField(choices=STATUS, max_length=12)

    class Meta:
        verbose_name_plural = "Author"

    def __str__(self):
        return self.first_name + self.last_name


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to = "blog/feature_image/", blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    status = models.CharField(choices=STATUS, max_length=10, default='active')
    featured = models.BooleanField(default=False)
    visit_count = models.IntegerField(default=0)
    visible = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Post"

    def __str__(self):
        return self.title


class EmailSubscribe(models.Model):
    email = models.EmailField()
    subscribe_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=50)
    body = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from .models import EmailSend


# class RegistrationForm(UserCreationForm):
#     fname = forms.CharField(label="First Name", widget=forms.TextInput(attrs={'class':'form-control'}))
#     lname = forms.CharField(label="Last Name", widget=forms.TextInput(attrs={'class':'form-control'}))
#     password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class':'form-control'}))
#     password2 = forms.PasswordInput(label="Confirm Password", widget=forms.PasswordInput(attrs={'class':'form-control'}))
#     email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={'class':'form-control'}))
#     class Meta:
#         model = User
#         fields = ['username', 'email', 'password1', 'password2']
#         widgets= {
#             username:forms.TextInput(attrs={'class':'form-control'})
#         }

class Password_Change_Form(PasswordChangeForm):
    old_password = forms.CharField( label='Current Password' , widget=forms.PasswordInput(attrs={'class':'form-control'}))
    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    new_password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))


class EmailSendForm(forms.ModelForm):
    class Meta:
        model = EmailSend
        exclude = ['sender_user', 'send_date']
        widgets = {
            'sender' : forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email'}),
            'subject' : forms.TextInput(attrs={'class':'form-control'}),
            'message' : forms.Textarea(attrs={'class':'form-control'}),
        }

templates/user/change_password_done.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title> Password Change Success </title>

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- Custom styles for this template-->

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <h2 class="py-3 text-center alet alert-success" role="alert">Password Change complete Successfully...</h2>
              <div class="col-lg-12">
                <div class="p-5">
                  <h1></h1>
                  <div class="alert alert-warning" role="alert">Your Password has been set.</div>
                  <hr>
                  <div class="text-center">
                    <a href="{% url 'home' %}">Return to home page</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
</body>

</html>

templates/user/changepassword.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> Login </title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block"> <img src="{% static 'images/login.jpg' %}" alt="">
                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    {% if messages %}
                                    <div class="messages">
                                        {% for message in messages %}
                                        <div class="alert{% if message.tags %} {{ message.tags }} {% endif %}"
                                            role="alert">{{ message }}
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        {% endfor %}
                                    </div>
                                    {% endif %}
                                    <form class="user" method="POST">
                                        {% csrf_token %}
                                        {% for fm in forms %}
                                        <div class="mb-3">
                                            {{ fm.label_tag }}
                                            {{ fm }}
                                            <small class="text-danger">{{ fm.errors|striptags }}</small>
                                        </div>
                                        {% endfor %}

                                        <input type="submit" class="btn btn-primary btn-user btn-block" name="" id="">

                                        <hr>

                                    </form>
                                    <!--       <form method="POST">
                                        {% csrf_token %}
                                        <input type="text" name="username" id="">
                                        <input type="password" name="password" id="">
                                        <input type="submit" name="" id="">
                                    </form> -->
                                    <div class="text-center">
                                        <a class="small" href="#">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'registration' %}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <!-- <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
   <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script> -->

    <!-- Core plugin JavaScript-->
    <!-- <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script> -->

    <!-- Custom scripts for all pages-->
    <!-- <script src="{% static 'js/sb-admin-2.min.js' %}"></script> -->

    <!-- Page level plugins -->
    <!-- <script src="vendor/chart.js/Chart.min.js"></script> -->

    <!-- Page level custom scripts -->
    <!-- <script src="js/demo/chart-area-demo.js"></script>
   <script src="js/demo/chart-pie-demo.js"></script> -->

</body>

</html>

templates/user/forget_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> Login </title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->

</head>
<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block"> <img src="{% static 'images/forget_password.jpg' %}" alt=""> </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    {% if messages %}
                                    <div class="messages">
                                        {% for message in messages %}
                                        <div class="alert{% if message.tags %} {{ message.tags }} {% endif %}" role="alert">{{ message }}
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        {% endfor %}
                                    </div>
                                    {% endif %}
                                    <form class="user" method="POST" >
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp" name="username"
                                                placeholder="Enter Username " required>
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" name="password" placeholder="Password" required>
                                        </div>
 
                                        <input type="submit"  class="btn btn-primary btn-user btn-block" name="" id="">

                                        <hr>

                                    </form>
                             <!--       <form method="POST">
                                        {% csrf_token %}
                                        <input type="text" name="username" id="">
                                        <input type="password" name="password" id="">
                                        <input type="submit" name="" id="">
                                    </form> -->
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'registration' %}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

   <!-- Bootstrap core JavaScript-->
   <!-- <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
   <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script> -->

   <!-- Core plugin JavaScript-->
   <!-- <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script> -->

   <!-- Custom scripts for all pages-->
   <!-- <script src="{% static 'js/sb-admin-2.min.js' %}"></script> -->

   <!-- Page level plugins -->
   <!-- <script src="vendor/chart.js/Chart.min.js"></script> -->

   <!-- Page level custom scripts -->
   <!-- <script src="js/demo/chart-area-demo.js"></script>
   <script src="js/demo/chart-pie-demo.js"></script> -->

</body>

</html>

templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> Login </title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->

</head>
<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <h2 class="py-3 text-center">User Login</h2>
                            <div class="col-lg-6 d-none d-lg-block"> <img src="{% static 'images/login.jpg' %}" alt=""> </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    {% if messages %}
                                    <div class="messages">
                                        {% for message in messages %}
                                        <div class="alert{% if message.tags %} {{ message.tags }} {% endif %}" role="alert">{{ message }}
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        {% endfor %}
                                    </div>
                                    {% endif %}
                                    <form class="user" method="POST" >
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            <input type="text" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp" name="username"
                                                placeholder="Enter Username " required>
                                        </div>
                                        <div class="mb-3">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" name="password" placeholder="Password" required>
                                        </div>
 
                                        <input type="submit"  class="btn btn-primary w-100">

                                        <hr>

                                    </form>
                             <!--       <form method="POST">
                                        {% csrf_token %}
                                        <input type="text" name="username" id="">
                                        <input type="password" name="password" id="">
                                        <input type="submit" name="" id="">
                                    </form> -->
                                    <div class="text-center">
                                        <a class="small" href="{% url 'reset_password' %}">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'registration' %}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

   <!-- Bootstrap core JavaScript-->
   <!-- <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
   <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script> -->

   <!-- Core plugin JavaScript-->
   <!-- <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script> -->

   <!-- Custom scripts for all pages-->
   <!-- <script src="{% static 'js/sb-admin-2.min.js' %}"></script> -->

   <!-- Page level plugins -->
   <!-- <script src="vendor/chart.js/Chart.min.js"></script> -->

   <!-- Page level custom scripts -->
   <!-- <script src="js/demo/chart-area-demo.js"></script>
   <script src="js/demo/chart-pie-demo.js"></script> -->

</body>

</html>

templates/user/password_reset_done.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title> Login </title>

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- Custom styles for this template-->

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <h2 class="py-3 text-center alet alert-success" role="alert">Password reset complete Successfully...</h2>
              <div class="col-lg-12">
                <div class="p-5">
                  <h1></h1>
                  <div class="alert alert-success" role="alert">Your Password has been set. You may go ahead and login</div>
                  <hr>
                  <div class="text-center">
                    <a href="{% url 'home' %}">Return to home page</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
</body>

</html>

templates/user/password_reset_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title> Login </title>

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- Custom styles for this template-->

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <h2 class="py-5 text-center">Welcome to the Password Reset Form</h2>
              <div class="col-lg-12">
                <div class="p-5">
                  <h1></h1>
                  <div class="alert alert-warning">Please enter your new password so we can verify.</div>
                              <!-- <form action="" method="POST">
                                {% csrf_token %} 
                                {{form}}                                        This tag used for default
                                <input type="submit" value="Reset Password"/>
                              </form> -->
                  <form action="" method="POST">
                    {% csrf_token %}
                    <div class="mb-3 row">
                      <div class="col-sm-6">
                        <input type="password" class="form-control" name="new_password1" autocomplete="new-password" required=""
                          id="id_new_password1" placeholder="New password">
                    </div>
                      <div class="col-sm-6">
                      <input type="password" class="form-control" name="new_password2" autocomplete="new-password" required=""
                        id="id_new_password2" placeholder="Confirm New password">
                      </div>
                    </div>
                    {% for fm in form %}
                            <small class="text-danger">{{ fm.errors|striptags }}</small>
                    {% endfor %}

                    <input type="submit" class="btn btn-outline-success float-end" value="Reset Password" /><br>
                  </form>
                  <br>
                  <hr>
                  <div class="text-center">
                    <a href="{% url 'home' %}">Return to home page</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'registration' %}">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
</body>

</html>

templates/user/password_reset_sent.html
<div class="text-center" style="width: 80%; margin: 0 auto">
   <h1>Password reset sent</h1> 
   <h5>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</h5><br>
   <h6 style="width: 60%; margin: 0 auto">If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</h6>
</div>
<div class="text-center">
  <a href="{% url 'home' %}">Return to home page</a>
</div>

templates/user/reset_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title> Login </title>

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <h2 class="py-3 text-center">Welcome to the Password Reset Page</h2>
              <div class="col-lg-6 d-none d-lg-block"> <img src="{% static 'images/login.jpg' %}" alt=""> </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <h1></h1>
                  <p class="text-danger small">
                    Forgot your password? Please <strong>enter the email address you used to register 
                    with us </strong> and we will send you a link to reset your password
                  </p>
                  <form action="" method="POST" class="text-center">
                    {% csrf_token %}
                    <!-- {{ form }}     This tag user for default input field -->     
                    <div class="mb-3">
                      <input type="email" autocomplete="email" class="form-control form-control-email"
                          id="id_email" name="email" placeholder="Email" required>
                    </div>
                    <input type="submit" class="btn btn-primary w-100" value="Send email" /><br>
                  </form>
                  
                  <hr>
                  <div class="text-center">
                    <a href="{% url 'home' %}">Return to home page</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'registration' %}">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
</body>

</html>